apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ix-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  resources:
    requests:
      storage: 256Mi